### ISSUE TITLE
guzzlehttp/guzzle[6.3.3] 版本问题

### ISSUE THREAD

**Issue by jamai** [luoxiaojun1992/laravel-tars#12]
guzzlehttp/guzzle[6.3.3] 版本问题
![image](https://user-images.githubusercontent.com/3272566/81540762-b0e5ef00-93a4-11ea-806d-c105951408c2.png)

**Comment by luoxiaojun1992** [comment]
感谢反馈，目前主要是guzzle v6和v7，考虑到v7对PHP版本要求比较高，改成了依赖guzzle v6大版本，请你更新后尝试，如果有问题请再提issue反馈。
