### ISSUE TITLE
支持 Laravel 最新版本v7.12.0吗？

### ISSUE THREAD

**Issue by dmf-code** [luoxiaojun1992/laravel-tars#13]
在介绍中没有看见支持 `Laravel` 的版本信息，请问支持最新版本吗？

**Comment by luoxiaojun1992** [comment]
你好，目前只能支持5.5，因为6.x和7.x都没有经过测试，而且受限于tars-server包引入的illuminate/routing和illuminate/events包的版本，后续可能会支持，由于laravel版本更新太快，会优先支持LTS版本。谢谢。

**Comment by dmf-code** [comment]
好的
