### ISSUE TITLE
laravel 5.7 compose didnot support

### ISSUE THREAD

**Issue by jestbon** [luoxiaojun1992/laravel-tars#15]
- luoxiaojun1992/laravel-tars 0.1.6 requires phptars/tars-server 0.5.0 -> satisfiable by phptars/tars-server[0.5.0].
    - Conclusion: don't install laravel/framework v5.7.29
    - Conclusion: don't install laravel/framework v5.7.28
    - Conclusion: don't install laravel/framework v5.7.27
    - Conclusion: don't install laravel/framework v5.7.26
    - Conclusion: don't install laravel/framework v5.7.25
    - Conclusion: don't install laravel/framework v5.7.24
    - Conclusion: don't install laravel/framework v5.7.23
    - Conclusion: don't install laravel/framework v5.7.22
    - Conclusion: don't install laravel/framework v5.7.21
    - Conclusion: don't install laravel/framework v5.7.20
    - Conclusion: don't install laravel/framework v5.7.19
    - Conclusion: don't install laravel/framework v5.7.18
    - Conclusion: don't install laravel/framework v5.7.17
    - Conclusion: don't install laravel/framework v5.7.16
    - Conclusion: don't install laravel/framework v5.7.15
    - Conclusion: don't install laravel/framework v5.7.14
    - Conclusion: don't install laravel/framework v5.7.13
    - Conclusion: don't install laravel/framework v5.7.12
    - Conclusion: don't install laravel/framework v5.7.11
    - Conclusion: don't install laravel/framework v5.7.10
    - Conclusion: don't install laravel/framework v5.7.9
    - Conclusion: don't install laravel/framework v5.7.8
    - Conclusion: don't install laravel/framework v5.7.7
    - Conclusion: don't install laravel/framework v5.7.6
    - Conclusion: don't install laravel/framework v5.7.5
    - Conclusion: don't install laravel/framework v5.7.4
    - Conclusion: don't install laravel/framework v5.7.3
    - Conclusion: don't install laravel/framework v5.7.2
    - Installation request for luoxiaojun1992/laravel-tars 0.1.6 -> satisfiable by luoxiaojun1992/laravel-tars[0.1.6].
    - Conclusion: don't install laravel/framework v5.7.1
    - Conclusion: don't install laravel/framework v5.7.0
    - phptars/tars-server 0.5.0 requires illuminate/events ~5.5.0 -> satisfiable by illuminate/events[5.5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - don't install illuminate/events 5.5.x-dev|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/events v5.5.0|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/events v5.5.16|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/events v5.5.17|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/events v5.5.2|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/events v5.5.28|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/events v5.5.33|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/events v5.5.34|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/events v5.5.35|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/events v5.5.36|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/events v5.5.37|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/events v5.5.39|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/events v5.5.40|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/events v5.5.41|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/events v5.5.43|don't install laravel/framework 5.7.x-dev
    - don't install illuminate/events v5.5.44|don't install laravel/framework 5.7.x-dev
    - Installation request for laravel/framework 5.7.* -> satisfiable by laravel/framework[5.7.x-dev, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.12, v5.7.13, v5.7.14, v5.7.15, v5.7.16, v5.7.17, v5.7.18, v5.7.19, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.24, v5.7.25, v
5.7.26, v5.7.27, v5.7.28, v5.7.29, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9].

**Comment by luoxiaojun1992** [comment]
请查看 https://github.com/luoxiaojun1992/laravel-tars/issues/13

**Comment by jestbon** [comment]
好的，感谢！

**Comment by jestbon** [comment]
> 请查看 #13
好的，感谢！
