### ISSUE TITLE
最新版获取 deploy_cfg 又不行了

### ISSUE THREAD

**Issue by dmf-code** [luoxiaojun1992/laravel-tars#20]
更新最新的代码后，发现 `config('tars.deploy_cfg')` 又不能获取到对应的值了 #17

**Comment by luoxiaojun1992** [comment]
App.php的 createApp方法调试一下，打印一下config信息，谢谢

**Comment by dmf-code** [comment]
![image](https://user-images.githubusercontent.com/22268578/97515195-8972f500-19cb-11eb-86c8-81f94d1cf774.png)
这里面是有 `config` 信息的，就是在跑定时任务的时候获取不到。
![image](https://user-images.githubusercontent.com/22268578/97515661-7ad90d80-19cc-11eb-9221-ca2c7462be3d.png)
![image](https://user-images.githubusercontent.com/22268578/97515713-9d6b2680-19cc-11eb-8b50-ca30167299a8.png)

**Comment by luoxiaojun1992** [comment]
如果是在provider中，没办法获取这个配置，只能通过App.php相关方法获取

**Comment by luoxiaojun1992** [comment]
定时任务是什么？cron跑command?

**Comment by dmf-code** [comment]
嗯嗯，那这个路径能不能写进文件，这样就不会存在获取不到的情况了，可以在所有情况下使用

**Comment by dmf-code** [comment]
> 定时任务是什么？cron跑command?

是的

**Comment by dmf-code** [comment]
因为存在业务会用到定时任务，所以写在内存中就会出现这种情况

**Comment by luoxiaojun1992** [comment]
那和tars没有关系了，tars必须依赖swoole，目前应该没有办法

**Comment by dmf-code** [comment]
这个可以框架优化一下嘛，路径写在文件其实就能够获取到配置文件路径了，这样就可以兼容定时任务的情况，不然现在要手动设置路径

**Comment by luoxiaojun1992** [comment]
不合适，你可以自己定制

**Comment by dmf-code** [comment]
好吧
