### ISSUE TITLE
用lumen 版本为5.5composer后，http请求报以下错误

### ISSUE THREAD

**Issue by wx1860** [luoxiaojun1992/laravel-tars#23]
Target [Illuminate\Contracts\Http\Kernel] is not instantiable.|#0 /data/tars/tarsnode-data/PHPTest.PHPServer/bin/src/vendor/illuminate/container/Container.php(758): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /data/tars/tarsnode-data/PHPTest.PHPServer/bin/src/vendor/illuminate/container/Container.php(631): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /data/tars/tarsnode-data/PHPTest.PHPServer/bin/src/vendor/illuminate/container/Container.php(586): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array)
#3 /data/tars/tarsnode-data/PHPTest.PHPServer/bin/src/vendor/laravel/lumen-framework/src/Application.php(230): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#4 /data/tars/tarsnode-data/PHPTest.PHPServer/bin/src/vendor/luoxiaojun1992/laravel-tars/src/App.php(37): Laravel\Lumen\Application->make('Illuminate\\Cont...')
#5 /data/tars/tarsnode-data/PHPTest.PHPServer/bin/src/vendor/luoxiaojun1992/laravel-tars/src/Route/TarsRoute.php(165): Lxj\Laravel\Tars\App::getApp(Object(Illuminate\Http\Request))
#6 /data/tars/tarsnode-data/PHPTest.PHPServer/bin/src/vendor/luoxiaojun1992/laravel-tars/src/Route/TarsRoute.php(119): Lxj\Laravel\Tars\Route\TarsRoute->app(Object(Illuminate\Http\Request))
#7 /data/tars/tarsnode-data/PHPTest.PHPServer/bin/src/vendor/luoxiaojun1992/laravel-tars/src/Route/TarsRoute.php(28): Lxj\Laravel\Tars\Route\TarsRoute->clean(Object(Illuminate\Http\Request))
#8 /data/tars/tarsnode-data/PHPTest.PHPServer/bin/src/vendor/phptars/tars-server/src/protocol/HTTPProtocol.php(35): Lxj\Laravel\Tars\Route\TarsRoute->dispatch(Object(Tars\core\Request), Object(Tars\core\Response))
#9 /data/tars/tarsnode-data/PHPTest.PHPServer/bin/src/vendor/phptars/tars-server/src/core/Server.php(683): Tars\protocol\HTTPProtocol->route(Object(Tars\core\Request), Object(Tars\core\Response))
#10 {main}

**Comment by luoxiaojun1992** [comment]
感谢反馈，已经尝试修复，可以使用dev-master版本测试一下，或者请暂时使用0.1.7版本，谢谢。

@wx1860
