### ISSUE TITLE
做重定向跳转的时候ios系统下很慢，导致请求超时

### ISSUE THREAD

**Issue by wx1860** [luoxiaojun1992/laravel-tars#27]
代码：
```
//如果没有openId，携带业务参数获取微信授权
        if(!isset($param['openid'])){
            //携带业务参数获取微信授权
            $auth_url = 'http://mp.fchomg.com/mp/auth/init';
           // $auth_url = 'http://web.user.com:8080/mp/auth/init';
            $back_url = $request->fullUrl();
            log::info($auth_url.'?back_url='.$back_url.'&app_id='.$appId);
            return redirect($auth_url.'?back_url='.$back_url.'&app_id='.$appId);
        }
```
1.这段在ios系统下任何浏览器转发都很慢(包括Mac safari下，Mac谷歌 火狐浏览器正常)；
2.在安卓系统下正常转发
3.用传统nginx代理无论哪个操作系统都正常转发

**Comment by luoxiaojun1992** [comment]
Mac上用Chrome控制台调试过吗？客户端收到带重定向header的response了吗？

**Comment by luoxiaojun1992** [comment]
> 1.这段在ios系统下任何浏览器转发都很慢(包括Mac safari下，Mac谷歌 火狐浏览器正常)；

是只在safari中不正常？任何浏览器是指哪些浏览器？
你现在的提供的信息还不能确定是否与集成tars有关。
1. 建议你用相应浏览器的控制台查看一下http响应，看一下响应时间，有没有包含什么特别的header。
2. 升级一下Mac系统或者试一下别的Mac电脑浏览器是不是正常。
3. 单独写一个纯Swoole的server api返回重定向测试一下。
