### ISSUE TITLE
var_dump回在调试的时候打印出来

### ISSUE THREAD

**Issue by github-lijiang** [luoxiaojun1992/laravel-tars#31]
src/vendor/luoxiaojun1992/laravel-tars/src/Route/TarsRoute.php文件64行

if (Util::isLumen()) {
            $auth = $application['auth'];
            $reflect = new \ReflectionObject($auth);
            $prop = $reflect->getProperty('customCreators');
            $prop->setAccessible(true);
            $cc = $prop->getValue($auth);
64            var_dump(isset($cc['api']));

            $illuminateResponse = $application->dispatch($illuminateRequest);
        }
注释一下var_dump

**Comment by luoxiaojun1992** [comment]
已删除，谢谢提醒
