### ISSUE TITLE
在项目里使用laravel服务提供者＋门面，方法里面查询的数据常住内存，每次进来都使用同一数据源

### ISSUE THREAD

**Issue by wx1860** [luoxiaojun1992/laravel-tars#33]
如何避免使用门面的时候查询数据后销毁变量

**Comment by luoxiaojun1992** [comment]
看不太明白，请提供示例代码和说明

**Comment by wx1860** [comment]
class PayServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        $this->app->singleton('pay', function ($app) {
            $config = $app->make('config')->get('pay');
            return new PayManager($config);
        });
    }
}
在PayManager这个类的__construct方法中写了数据库查询数据，每次请求进来都查到的是同一数据，修改数据库必须重启tars服务才生效

**Comment by luoxiaojun1992** [comment]
Provider 的 register 应该只会执行一次，而且 Provider 在请求所有接口的时候应该都会执行，包括执行脚本。是否可以尝试用 middleware 实现。
