### ISSUE TITLE
用lumen框架没办法使用laravel-zipkin扩展包吗

### ISSUE THREAD

**Issue by wx1860** [luoxiaojun1992/laravel-tars#34]
用lumen框架没办法使用laravel-zipkin扩展包吗，看了源码在lumen下好多类找不到

**Comment by luoxiaojun1992** [comment]
> 用lumen框架没办法使用laravel-zipkin扩展包吗，看了源码在lumen下好多类找不到

laravel-zipkin 是单独的 package，当时没有适配 lumen

可以试试这些 package：
https://github.com/luca-giardina/lara-zipkin
https://github.com/Vinelab/tracing-laravel
